name: Pull request check

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - edited
      - synchronize

jobs:
  build:
    name: Pull request check
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    if: github.event.pull_request.user.login != 'renovate[bot]'

    steps:
      - run: pip install --upgrade attrs
      - uses: actions/checkout@v4

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --pre c2cciutils[pr_checks]

      - name: Check pull request
        run: c2cciutils-pull-request-checks
        env:
          GITHUB_EVENT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
