name: Auto reviews, merge and close pull requests

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  auto-merge:
    name: Auto reviews pull requests from bots
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Print event
        run: echo "${GITHUB}" | jq
        env:
          GITHUB: ${{ toJson(github) }}
      - name: Print context
        uses: actions/github-script@v7
        with:
          script: |-
            console.log(context);
      - name: Auto reviews GHCI updates
        uses: actions/github-script@v7
        with:
          script: |-
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
            })
        if: |-
          startsWith(github.head_ref, 'ghci/audit/')
          && (github.event.pull_request.user.login == 'geo-ghci-test[bot]'
            || github.event.pull_request.user.login == 'geo-ghci-int[bot]'
            || github.event.pull_request.user.login == 'geo-ghci[bot]')
      - name: Auto reviews Renovate updates
        uses: actions/github-script@v7
        with:
          script: |-
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
            })
        if: |-
          github.event.pull_request.user.login == 'renovate[bot]'
